project:
  type: website

website:
  title: "DisasterLens"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Project"
        href: project.qmd
      - text: "Source Code"
        href: code.qmd
      - text: "References"
        href: references.qmd
    right:
      - text: "About Us"
        href: about.qmd

format:
  html:
    theme:
      light: sandstone
      dark: slate
    css: styles.css
    toc: false
    toc-depth: 2
    page-layout: full
